# firebase-hosting-merge.yml

hosting:
  target: dexcoder  # Replace with your Firebase project name
  public: public  # Replace 'public' with the directory containing your static assets
  ignore:
    - firebase.json
    - firebase-debug.log
    - node_modules/**  # Adjust as needed for files to ignore
